# Generated by Django 3.2.8 on 2023-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0002_auto_20231207_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='66c8cd8b-a', max_length=10),
        ),
    ]
