# Generated by Django 3.2.8 on 2023-12-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0003_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='951e603b-7', max_length=10),
        ),
    ]
