# Generated by Django 3.2.8 on 2023-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='26ec3e7d', max_length=8),
        ),
    ]
