# Generated by Django 5.0 on 2023-12-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoview',
            name='device_os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
